DEF VAR Sequel AS HANDLE.

DEF {&NEW} SHARED VAR SequelCon AS COM-HANDLE NO-UNDO.
DEF {&NEW} SHARED VAR SequelCmd AS COM-HANDLE NO-UNDO.
DEF {&NEW} SHARED VAR SequelRes AS COM-HANDLE NO-UNDO.
DEF {&NEW} SHARED VAR SequelLog AS LOGICAL INIT NO NO-UNDO.

&IF DEFINED(LOG) = 0 &THEN
ASSIGN SequelLog = YES.
&ENDIF

&IF DEFINED(Sequel) = 0 &THEN
RUN Sequel.p PERSISTENT SET Sequel.
&ENDIF
